Allow multiple selectors (array of selectors)
This avoids the error: init.standard.js:15 Uncaught TypeError: options.selector.substring is not a function

when multiple selectors are created by stfalcon_tinymce.selector in YAML and it is merged with Twig function tinymce_init({selector:'textarea.tinymce'})